DROP TABLE IF EXISTS quality_gate_run CASCADE;
DROP TABLE IF EXISTS agent_run CASCADE;
DROP TABLE IF EXISTS stage_run CASCADE;
DROP TABLE IF EXISTS pipeline_run CASCADE;
DROP TABLE IF EXISTS pipeline_version CASCADE;
DROP TABLE IF EXISTS pipeline CASCADE;
